name: build

on:
  push:
    branches: [ Phase05-TDD ]
  pull_request:
    branches: [ master ]


jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301

    - name: Install dependencies
      run: dotnet restore
      working-directory: Projects\Phase05-TDD\InvertedIndex
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: Projects\Phase05-TDD\InvertedIndex
    - name: Test
      run: dotnet test --no-restore --verbosity normal --collect:"XPlat Code Coverage"
      working-directory: Projects\Phase05-TDD\InvertedIndex
